import type { Metadata } from "next";
import "./global.scss";

export const metadata: Metadata = {
  title: "airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        layout<br/>
        {children}
      </body>
    </html>
  );
}
